export {Duration} from '@/shared/ui/duration/Duration'
export {NextButton,PrevButton} from './sliderButtons/customSliderButtons'
export {AutoPlaySlider} from './autoPlaySlider/autoPlaySlider'
export {SliderWithButtons} from './sliderWithButtons/slider'
export {Button} from './Button/Button'
export {Rating} from './Rating/rating'