export const getImg = 'https://image.tmdb.org/t/p/original/'
export const UpcomingMovies = '/movie/upcoming'
export const TopRatedMovies = '/movie/top_rated'
export const NowPlayingMovies = '/movie/now_playing'
export const Popular = '/movie/popular'
